version: "3.7"

services:
  redis:
    image: "redis:alpine"
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "6371:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped